services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    depends_on:
      - maria_db
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lvl-network

  # Nginx service
  web-server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lvl-network

  # Database service
  maria_db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ats_db
      MYSQL_USER: karem
      MYSQL_PASSWORD: 1234
    # MYSQL_DATABASE: ${DB_DATABASE}
    # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    # MYSQL_PASSWORD: ${DB_PASSWORD}
    # MYSQL_USER: ${DB_USERNAME}
    ports:
      - 3306:3306
    networks:
      - lvl-network
    volumes:
      - maria_db:/var/lib/mysql

  # PhpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - maria_db
    ports:
      - 8081:80
    environment:
      PMA_HOST: maria_db
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - lvl-network

  filebeat:
    image: elastic/filebeat:8.10.2
    container_name: filebeat
    user: root
    platform: linux/amd64
    volumes:
        - ./.docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
        - ./storage/logs:/var/log/laravel
    command: ["--strict.perms=false"]
    environment:
        - monitoring.enabled= true
    depends_on:
        - app
    networks:
        - lvl-network

# Docker Networks
networks:
  lvl-network:
    driver: bridge

# Docker Volumes
volumes:
  maria_db:
