services:
    ### Container for laravel application: php8.2, nginx-fpm , maria db and phpmyadmin
    # PHP service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            working_dir: /var/www
        depends_on:
            - maria_db1
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - lvl-network

    # Nginx service
    web-server:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - lvl-network

    # Database image
    maria_db1:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: ats_db
            MYSQL_USER: karem
            MYSQL_PASSWORD: 1234
            # MYSQL_DATABASE: ${DB_DATABASE}
            # MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            # MYSQL_PASSWORD: ${DB_PASSWORD}
            # MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3306:3306
        networks:
            - lvl-network
        volumes:
            - maria_db1:/var/lib/mysql
            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf

    # PhpMyAdmin
    phpmyadmin1:
        depends_on:
            - maria_db1
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: maria_db1
            MYSQL_ROOT_PASSWORD: 1234
        networks:
            - lvl-network

    # Filebeat service for log collection and forwarding to Elasticsearch
    filebeat:
        image: elastic/filebeat:8.10.2
        container_name: filebeat
        user: root
        platform: linux/amd64
        volumes:
            - ./.docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./storage/logs:/var/log/laravel
        command: ["--strict.perms=false"]
        environment:
            - monitoring.enabled= true
        depends_on:
            - app
        networks:
            - lvl-network

#Docker Networks
networks:
    lvl-network:
        driver: bridge

#Docker Volumes
volumes:
    maria_db1:
        driver: local
