services:
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: es
    restart: unless-stopped
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: false
      bootstrap.memory_lock: true
      xpack.license.self_generated.type: basic
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic

  logstash:
    image: logstash:8.10.2
    container_name: log
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
      - ./logstash/nginx.log:/home/nginx.log
    ports:
      - 5000:5000/tcp
      - 5000:5000/udp
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config

  kibana:
    image: kibana:8.10.2
    container_name: kib
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  elastic_data: {}

networks:
  elastic: